export const LOGO_TEST_ID = "LOGO_TEST_ID";
export const ADD_PATH_FORM_TITLE_TEST_ID = "ADD_PATH_FORM_TITLE_TEST_ID";
export const ADD_PATH_BUTTON_TEST_ID = "ADD_PATH_BUTTON_TEST_ID";
export const CLOSE_ICON_TEST_ID = "CLOSE_ICON_TEST_ID";
export const STAR_ICON_TEST_ID = "STAR_ICON_TEST_ID";
export const PATH_LIST_CONTAINER_TEST_ID = "PATH_LIST_CONTAINER_TEST_ID";
export const PATH_DETAILS_VIEW_TEST_ID = "PATH_DETAILS_VIEW_TEST_ID";
