export const texts = {
  saunter: "Saunter",
  addPath: "Add path",
  noItemsFound: "No Items Found",
  addNewPath: "Add new path",
  title: "Title",
  shortDescription: "Short description",
  fullDescription: "Full description",
  length: "Length",
  clickToAddMarker: "Click to add marker",
  addToFavorites: "Add to favorites",
  removeFromFavorites: "Remove from favorites",
  remove: "Remove",
  selectPath: "Select any path",
  addMarkers: "You need to add at least two markers on map",
  pathAdded: "New path has been created",
  pathRemoved: "Path has been deleted",
  pathAddedToFavorites: "Path has been added to favorites",
  pathRemovedFromFavorites: "Path has been removed from favorites",
  titleRequired: "Title is a required field",
  selectAnyPath: "Select any path",
};
